/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ARCH_X86 0

#define ARCH_X86_64 0

#define CONFIG_ASM 0

// #define CONFIG_FONTCONFIG 1

#define CONFIG_ICONV 1

#define CONFIG_LARGE_TILES 0

#define CONFIG_LIBPNG 1

#define CONFIG_SOURCEVERSION "meson, commit: 0.17.3-81-g695509365f152bd28720a0c0e036d46836ee9345"

#define CONFIG_UNIBREAK 1

#define HAVE_FSTAT 1

#define HAVE_STRDUP 1

#define HAVE_STRNDUP 1

